# projects/text_classification/environment.yml
name: ml-learning
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - scikit-learn
  - numpy
  - pandas
  - jupyter
  - pyarrow
  - pillow
  - opencv
  - datasets
  - beautifulsoup4
  - requests
  - pip
